name: Deploy Angular App to VPS

on:
  push:
    branches:
      - main # Se activará el workflow cuando haya un push en la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: ng build --configuration=production

    - name: Deploy to VPS
      env:
        HOST: ${{ secrets.VPS_HOST }}
        USERNAME: ${{ secrets.VPS_USERNAME }}
        PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        echo "Deploying to VPS..."
        scp -o StrictHostKeyChecking=no -r dist/browser/* $USERNAME@$HOST:/var/www/calch.ajustadoati.com
